server:
  ingress:
    enabled: true
    ingressClassName: nginx-public
    annotations:
      kubernetes.io/ingress.class: nginx-public
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - prometheus.jppol.click
    tls:
      - secretName: prometheus-jppol-click-secret
        hosts:
          - prometheus.jppol.click
