server:
  ingress:
    enabled: true
    ingressClassName: nginx-public
    annotations:
      kubernetes.io/ingress.class: nginx-public
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - prometheus.jppol.click
    tls:
      - secretName: prometheus-jppol-click-secret
        hosts:
          - prometheus.jppol.click
          - prometheus1.jppol.click
extraScrapeConfigs: |
  - job_name: karpenter
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - $KARPENTER_NAMESPACE
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_endpoints_name
      - __meta_kubernetes_endpoint_port_name
      action: keep
      regex: karpenter;http-metrics
