admin:
  existingSecret: "grafana-admin-credentials"
  userKey: admin-user
  passwordKey: admin-password
persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  ingressClassName: nginx-public
  # Values can be templated
  annotations:
    kubernetes.io/ingress.class: nginx-public
    cert-manager.io/cluster-issuer: letsencrypt
  labels: {}
  path: /
  pathType: Prefix
  hosts:
    - grafana.jppol.click

  tls:
    - secretName: grafana-jppol-click-secret
      hosts:
        - grafana.jppol.click
        - grafana1.jppol.click
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://grafana-loki-gateway
        access: proxy
        isDefault: false
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 37
      datasource: Prometheus
    ingress-nginx:
      gnetId: 21336
      revision: 1
      datasource: Prometheus
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
    karpenter-capacity:
      url: https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
    karpenter-performance:
      url: https://karpenter.sh/preview/getting-started/getting-started-with-karpenter/karpenter-performance-dashboard.json

envValueFrom:
  GF_AUTH_GITHUB_CLIENT_SECRET:
    secretRef:
      name: grafana-github-client-secret
      key: client-secret

grafana.ini:
  security:
    allow_embedding: true
  server:
    domain: grafana.jppol.click
    root_url: https://grafana.jppol.click
  auth.github:
    enabled: true
    allow_sign_up: true
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    team_ids:
    allowed_organizations: jppol-idp
    role_attribute_path: "contains(groups[*], '@jppol-idp/grafana-admins') && 'Admin' || contains(groups[*], '@jppol-idp/grafana-editors') && 'Editor' || 'Viewer'"
    client_id: Ov23li7KYYtuHPdEfKZt
    client_secret: $__env{GF_AUTH_GITHUB_CLIENT_SECRET}
    allow_assign_grafana_admin: true
