image:
  tag: v0.9.9
ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: nginx-public
    hosts:
      - host: start.jppol.click
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - start.jppol.click
          - start1.jppol.click
        secretName: start-jppol-click
config:
  services:
    - IDP:
        - ArgoCD:
            href: https://argocd.jppol.click
            description: GitOPS
        - Grafana:
            href: https://grafana.jppol.click
            description: Metrics and logs
        - Start:
            href: https://prometheus.jppol.click
            description: Test - needs auth and exposed only internally if at all
