kubecostToken: "bHluZXRrQGdtYWlsLmNvbQ==xm343yadf98"
persistentVolume:
  enabled: true

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: kubecost-basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  className: nginx-public
  enabled: true
  hosts:
    - kubecost.jppol.click
  tls:
    - hosts:
        - kubecost.jppol.click
      secretName: kubecost-tls

kubecostProductConfigs:
  currencyCode: USD

kubecostMetrics: # Needed by backstage-kubecost plugin
  emitPodAnnotations: true
  emitNamespaceAnnotations: true

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model

forecasting:
  fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.16

networkCosts:
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs
    tag: v0.17.6

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

prometheus:
  server:
    image:
      repository: public.ecr.aws/kubecost/prometheus
    persistentVolume:
      enabled: true

  configmapReload:
    prometheus:
      image:
        repository: public.ecr.aws/kubecost/prometheus-config-reloader

reporting:
  productAnalytics: false
