global:
  priorityClassName: system-cluster-critical

loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    aws:
      s3: s3://eu-north-1/jppol-idp-eks-001-grafana-loki

  # storage:
  #   type: s3
  #   bucketNames:
  #     chunks: jppol-idp-eks-001-grafana-loki
  #     ruler: jppol-idp-eks-001-grafana-loki
  #     admin: jppol-idp-eks-001-grafana-loki
  #   s3:
  #     s3: null
  #     region: eu-north-1
  #     s3ForcePathStyle: false
  #     insecure: false

  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

  compactor:
    # working_directory: /data/retention
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3

chunksCache:
  enabled: true
  allocatedMemory: 1024

serviceAccount:
  create: true
  name: loki
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::970547334392:role/LokiStorage-eks-001

deploymentMode: SimpleScalable

backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 2

# Enable minio for storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
