crds:
  enabled: true
dnsPolicy: "None"
podDnsConfig:
  nameservers:
    - "1.1.1.1"
    - "8.8.8.8"
dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
config:
  logging:
    verbosity: 2
    format: text
